// <auto-generated />
namespace Wirecraft.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class df : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207190742333_df"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAN1c224bORJ9X2D+odFPswuMZDtZYCaQM4ileCHMOg4iJ3k0qG5KJqZv6WYb1rftw37S/MKQfWXz3hfLSl6CiJdisXhYrKqu8l//+//i96cwcB5hmqE4unTPZ2euAyMv9lG0v3RzvPvlV/f3tz/9Y/HeD5+cL/W4V3QcmRlll+4Dxsmb+TzzHmAIslmIvDTO4h2eeXE4B348vzg7+21+fj6HhIRLaDnO4lMeYRTC4gf5uYwjDyY4B8FN7MMgq9pJz6ag6nwAIcwS4MFL9ytKoZcCQv8r3M7K8a7zLkCA8LKBwc51ktdvPmdwg9M42m8SgBEI7g4JJP07EGSw4vxN8tqW+bMLyvwcRFGMCbk4GrR5t9kW2dh7IgB8oGwVm7t0P6axn3uYHUSG/QEPnQbSRAYmMMWHT3BXTU3KqeuV68y70+f8/Ga2OJXycumuI/zqwnU+5EEAtgFsREZkusFxCv8DI5gCDP2PAGOYEiysfVjsRVicWyoi/9arkLMhAHOda/QE/f/CaI8fmpVuwFPd8m+Css8RInAkc3CaQ5ax8rd+zSRFXrPoKs7JRMne9DR8mHkpSspj78U++e9I/ukl2WAQJs0eiOjvUGixiw/gEe0LsHI0dyiA5MZ8gkHRmz2gpLw4swqC99WI6zQOP8VBi82y434T52kh1VjWewfSPcRddhbzFu7aS3AVxNshN2BL5g2Bfz3vJLGvA78dcgEG9apXKALpwQ6yPZfBZIFmcxRH9BTvisa+lAbC3RpfyzzDcQjTIRjzqrlDcMbOPUmsjYXaFqX4YQUO/fXUETRe8hDjWKrxajzcV0NaldftEXQe1y1TejqO4tQnppSepXqMhKeyS81U1T9KFd9SGkPuSbH4kEvSTHzuG+KjzIuJBTrSMLC/1Ho6GbEp86yjQQvhb6r2nuQKMdJb85J3kaMEfD+FWdZTLb0e8ASqlUBppcgvXSHv+3ZIe+e6PcKV47r76oEaQmM1"
                       + "Qb2uShPUbA/XBGsMw0l9k2l1h7UfY3F3xhL5loNKDfWiYkKuGrj0bO6bURx22U45fDsjRr0ZlSewir0RUCGzRyCgmj35E6I8HepC6LwpwtB9OUbwp+oulUfV9Pc7lDzkPKrSFl9n1wHYt0GQzxE5++BAFDErrO6ub2C4hWlFah2CPZn3BQQ5+XUmiKgzmGKgHnquH/oF+TBuBl/oB9/iB6ouq8GvRJmUu9dIpPO2jhbKLg+I3xtA31YwRDEnCTPcIJwERn7xVsrFI9/xuyyLPVQAsnszK9e+u977yHe0fn5rl9RBKucmDzBKAuQRBJItz2bnLn/Bb6MVDCCGzjsPF0HDJcg84IuKj2zBt+Ooeea6vibPzr94GTHy0IuJ8wdUXKmcg5atxtHUs6ajarnZQvZD9ys+HyrmNG8JZ7YWlkKPbavfIDPwJkUdeYlgStU/CJZEk+MUoAiLzxaKPJSAwMQ9N7G3cTRvVuJ7VpAqBcKo6WhGs9CsxInOJKm+CGwtby1IJGY4h71nxYeSGwlee9yE4bAT5GFz4AoTuz/ihP2PXP0IYOM9KqMm5gMtZgX/TIhTOnyGCzAR3BQCsTlxddi0F+QUAhjPwRFgx3sCBmNHdAuEd7Cwrk12gJa2pXVha1qUvggRFCZiaozXzbdgtaWN8Em0LOiEDcRCeKZ1a/i3X9hclwTdl2x+uS/D5BokMgLtXTcQqQM1AoXqbhqmN4+GkkT5ohjItEetkWaBII4Qc7YCtfqjIDNG+tWQv18m56JhnoWAcEtNDgFDpUIBr1u7e7PYN/9pQNy4zlmwcRcYphn0afaucBCeYfOSsJK4f4PzYOk+MNyz+NeIQe0wWIBpqDCY4LBCEgoj1saMZfiuVYhp/6L1aSXIMRehZk1zE2R2lZVlNfwucAaRUZQDJCBE8pRKUP7EWz3yDOMdBW7WhcKbPkIh1FHF5iVv+hbzMheraljMFUlbixuQJCjaM0lcVYuzKTO4lr9s+udP"
                       + "hSWNuZdJ0qgabpuVcJyCPeR6ydKE02uUZngFMNgCGvFb+qEwzMZuqZfizBfxtOr3t55A/19OkqWyNdaOaNlWBK7JzkJqGBchbBE24kyH5tGBAKTqjybLOMjDyBgSUNMqsw5YMmWLPYUqV6vLCeK/WulpdHK1WEqdDnt6zBdQlhrTLNJazLmDElwOAROCH9jFmBUCy5s+Gn5iBlZBx4Q9+TSVWOu0K1am8hQuHZXxkCsTpDo4KVp6AKT4tNLBRtHyQ0KsfZlHw0yeiFXQMkFNPVUlYjYAwMpYFxhQUxsPuzZZqnMBmtYfEjxK07AnciR5SVawUcxTSbYJVLJyVUYv1XTaXKOOmmla7SlNi+I66YilVLfZU2FyjQQ5lc3Pi2UVrSbfiKXUNJ7MnWD8tGnuhZilUxCzuhvyucewHae6a23iDUuobT2Zc2cdvKkcBiHpxurkdZMNR19l2khOX5rBcwxxd91aqczrOKadUOvR9mKj7jknL2ngU5TNRNes+IxUU+nLnPKrymgzXssWcbV9VHwwWWc0WatJx7HaMx/O6A0NPtRrabvWw20NVIn05RHdEeIv6Qw6BCN3/ZA7xFyZACSa/Y/GiRAHtNbM1fgp1Agf7Tv2XTUzNkjD9X5N1Eyaz1mIcvJDmoeqiXZyUc1FFWE016sKIcdyiOsQ3h+RX4QbDxmxvWZ0wGzzLVgGCFLXoB5wAyK0gxm+i/+E0aV7cXb2K1fwOqAYdZ5lfvBdVKQiKgtjum7PHO3SZS8XiB5B6j2AVCiJGlFrugtigKcoNa2Z+zkET/8cXT7qE+nhCevpXrZe86WQcTaqEpPQ3BbFmMKR9q62LAQwtqhnakycTo3lKWiOQdWTlkcy3eFKtFnHkJLCTdRA309x4bNAg68rHPYIKHA8qqhwCAWhjvAEUMnVEUrv32ujfv6xK98Gn/U4EnzVm5nGd1tW9izKQ6tq7VS2AQn2+npwYcxV4xb3qlhxZJk9A+tpBuU3K756"
                       + "2xquzpBMZrvyDEM85wST5l8yTb7Ksz1yVvwx8+BVnz/7Lnis0h6r4rI60nDsii9JTulRq3jUuV79zIkBtWI/XHHYyxaDHR069npgsoIva9i8bJEXH3UfZavYldRYluh8h8aK9uNynxWPd/B2Ne4nUdZ+dOgc/8HpCaDjvjjyqjUxSZw/Rmm9la5yrfzmc+n6W/p5uXTHPqoqVHj6pV5SlLXJKF9Jk/55sq1pril4k5Ffqgo05AVt6nI4GfFbedGGslROXymnXEFeHKOupDMU0mnOV1bF8ewVZyxk2vxsm3qazixl4eOJVBFZMSszFYW80BMsmePUSqfEw6o8Tl4SdoIFcebzOPIGhcSNMQVf/e+iqHb4bJHJtjhZWW9vmE65yR5Va2LeBrEfmL9GTgyYDO1bEjTtKIJex3JoxqyjXVzbMBxH9RAuRnsDMaAfg9+lGO2Ah0m3B7OM/QtP78Mt9NfRbY6THJMtw3AbdJJXqSGkW78ozevyvLgtkgqyKbZA2ET0A85tdJWjoP1DVteSCL+CBLWwqtA5PUtMQ+j7Q0PpQxxZEqrE1xiGdzBMAkIsu4024BGqeTPLsCuxxQqBfQrCrKLRzic/Cfz88Ont3yK16DVPXwAA"; }
        }
    }
}
