// <auto-generated />
namespace Wirecraft.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class sf : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207190740127_sf"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1d224bORJ9X2D/odFPuwuMZDtZYCaQZxBL8ULYdRxETubRoLopmdi+pZttWN+2D/tJ+wvDvvNO9kWyEuzLIGqSxWLVYbGqyPL87z//Xfz2EgbOM0wzFEfX7uXswnVg5MU+ivbXbo53P/3s/vbrn/+0+OCHL87Xpt+boh8ZGWXX7hPGybv5PPOeYAiyWYi8NM7iHZ55cTgHfjy/urj4ZX55OYeEhEtoOc7icx5hFMLyB/m5jCMPJjgHwV3swyCrv5OWTUnV+QhCmCXAg9fu7yiFXgoI/d/hdlb1d533AQKElw0Mdq6TvH33JYMbnMbRfpMAjEDwcEggad+BIIM15++St7bMX1wVzM9BFMWYkIujQYt322WRhX0gAsCHgq1ycdfupzT2cw/TnUi3f8ID84F8Ih0TmOLDZ7irhybV0PXKdebs8Dk/vh0tDi14uXbXEX5z5Tof8yAA2wC2IiMy3eA4hf+AEUwBhv4ngDFMCRbWPizXIkzOTRWR/zazEN0QgLnOLXqB/r9gtMdP7Ux34KX58neCsi8RInAkY3CaQ5qx6rd+ziRFXjvpKs7JQMna9DR8mHkpSiq192Kf/HMk/8Um2WAQJu0aiOgfUGixio/gGe1LsHI0dyiAZMd8hkHZmj2hpNo4sxqCj3WP2zQOP8dBh82q4XET52kp1VjW+gDSPcQsO4t5B3ftJrgJ4u2QHbAl44bAvxl3ltjXgd8OuQCDZtYbFIH0YAfZntNgMkG7uAJHhRYfyo99KQ2EuzW+lnmG4xCmQzDm1WOH4Iwee5ZYGwu1LUrx0woc+tupE1i85CnGsdTiNXh4rLt0Jo9tEWwe1ywzejqO4tQnrpSepaaPhKeqSc1U3T7KFN8XNIbsk3LyIZukHXjsHeKjzIuJBzrSMbDf1Ho6GfEp84yxoKXwN/X3nuRKMRa75jX3IkcJ+H4Ks6ynWXo74AhUG4HKS5FvulLej12Xbs+xLcKW45r72oEG"
                       + "QmMtQTOvyhI0bA+3BGsMw0ljk2lth3UcY7F3xhL5loPaDPWiYkKuGriFbh7bXhx26UY5fJkeo86MOhJYxd4IqJDRIxBQj578CBmknU4eMvWIrarQiu7S18QUIY6JuaqPlLOiScdW2d4PNHnIRXxVrLDObgOw75I0XyKCzeBADgpameyq72C4hWlNah2CPRn3FQQ5+XUhiIjpXGC06Xqp7/oV+TBuO1/pO9/jp8Kc153fiDKpVq+RCHP2jxbKLg9IXB5A31Yw5OBIEqq7QTgJjPzyLJeLR77i91kWe6gEJGs56tQDO9+HyHe0eYjOb2qSaM5dHmCUBMgjCCRLns0uXd4A3UcrGEAMnfceLpOaS5B5wBcNM1mCb8dRewyzsTDPzt94GVHy0IuJi1dUXKmCl46tNhDWs6ajarnYUvZD1ysebyrmNGcd51aXnkyPZavPSDPwJkUdOSlhWhxPIFgSS45TgCIsHqso8lACAhP33MDeztu8nYlvWcHCKBBGTaoZzUI7Eyc6k6T6IrCLDLQgkYQJHPaOig8lNxK89tgJw2EnyMNG4YoQoD/ihPWPnP0EYOMjPqMl5hNBZgN/JMQpA1LDBpgIbgqB2GhcndbtBTmFAMZzcALYScIUg78jjVmE07D0sU3egIl8n8N2qJvBh0IW7LFx0bRLZ2Iqg3tlu+gqGCNIwQQnrfe++RastsVH+CLqvBiwgVjIn3VxHa8PYXEsiWJdsvHVugyDm10iI9AZOwORJpMmUKiNk2F4e2oqSVRHqoFMp2qNNEsEcYQo3QrUmltbqo/0Wpc3MKboqmWehoBgpkwREUWlRgF/uLBrs1g3f3cjLlwXLdnESxTTFPo0a1dESEdYvCTvJ67fED1Zxk8U9zT+NWJQR0wWYBoqDCp7r5CEwou38eMpvhsTYlq/6H5bCXLMRmhY0+wEmWNp5VoO3wucR2gU5QAJyPKsSjuodHNsHR1qBYwlNxtFmV9znC0hJHe14hCdHiu3"
                       + "Z5wgGC9nhIlsEs2tb9O2LebV88H6w2KueGe4uANJgqI99e6w/uJsqkeHy582/Z/8hRWNucfsN94Ta2fCcQr2kGslUxNOb1Ga4RXAYAuKJPDSD4VuNp5cMxXn0InaajySZkDx72qQ7PVl6/+JwU5N4JasLCxipfLWRYSNONIpnn6CAKTqe75lHORhZMwSqWlVD2VoMtUXewr180KWE8RftOppMM8LaUpMgz096tKepkZ9Fmkt5pyihChUwISQGmAxZoXAaqePhp/4aLCkY8KefJhKrM1LQVqm8leHOirjIVe96WNwUn7pAZDyto3BRvnlh4RY56uMhpn87WBJywQ19VCViOmcEC1jXa5ITW087Lr3fcwGaL/+kOBROss9kSN5SmcFG8U4lWTb3DUtV2VCW02nex7HmJn2qz2laVHcvJOjKTXf7KlQz+MEOVWfj4tlFa32iRxNqf14NnuCilyn2Rfiw7KSmNXekI89he841V7r3orRhLqvZ6N3OsCbKmAQ3olZaV432KD6+nGYRPvSR2enEDcb1kpl3mR27YTa9LYXWxGec/KSpoJF2fTZZg1J7YU+xUlfJpUXbqPdeS1bJOT2UXmVtM6Kd4btS61ea+fTG72hwifDLX3ZprutwyrRgjznPUINFZ1ByjBy1w/JQ9yX8WDRrX80TmSZUmtj3Q2ZwrhIkqHjLMzklkWS/O3HYe/zRs3nlJqvMsL2aq/6T6VzOu97amttZuz89Szku/kurcvS5r25/PaizjWbi+2F5HPVxXUI78/ILxPPh4x44bOiw2zzLVgGCBZBYtPhDkRoBzP8EP8bRtfu1cXFz1y1/oBK+nmW+cF3UU6PosZa6moNehaYVMmbaoLoGaTeE0iFes4RhfK7IAZ4ijr5hrm/hODlr6Nr330iPTxhMfDrFpu/FjIuRpWRE5rbspJcUGnvUvFSAGMrEqfGxPkUiJ+D5RhU+m2pkumUK7FmjAsthZtogb6fyuijQIMvih52"
                       + "CChwPKoieggFoQj6DFDJFUFL999bo33+sct2B+t6HAm+ZNdM47utiT2K8ZhEj1p7bUVBkmcbafwHl+DdtDF2r9o4hkb3rHlQ5d6gSgrFYwpbL9gZUjNhVwhmSAueYXnOaxbk1A/aT1x/c8qKG9Wtet8JT1VEaFXG+olOyp6wtlTyePuk9YLSdI1Cndo8b/+q1B+uDPV1y05PDh17OzBZaak1bF63nFRyczOJ3bEpYrMsivtuzYf69uMs7Qd/mzPKbT1HBJzSb+2p+1f1WZlHElNs/6P/LZX/Gw9+UklYewIsySuGxXIUXp3SWldd1XB1p3jt+tvi4UoVoX9SlULx9Cv7pCgpllG+kZYX8WS7aE1TbCwjv1QVx8mLidWlyDLi9/KCOWWZsr5KWTmDvDBRXcVsKGLW6FdWL3b0al8aMl0liE0tIzNKWXR+JhWcVszKogfhBfoZlitzZoUpJrMqTZaX455hMbJZHydeoCSqmKjYtrc2RRPEv0w6s0ra/qbnhEuc7C9IvKoee5QDi8+giLtE/Z9JiN+WoX1Honi/GUGPcZTaPutoFzeuG8dR04W7rbiDGBRvK96nGO2Ah0mzB7OM/muKH8It9NfRfY6THJMlw3AbMFUBhd+nm7+seWZ5XtyXb3SyKZZA2ETFfeh9dJOjoPujkbeSCzMFicKhrG+iCl3i4kZqf2gpfYwjS0K1+Fo/+AGGSUCIZffRBjxDNW9mGbISW6wQ2KcgzGoa3Xjyk8DPD19+/QPxSpqtW2cAAA=="; }
        }
    }
}
