// <auto-generated />
namespace Wirecraft.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class addedmoredata : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207181219395_added more data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAN1c3W7bOhK+X2DfQdDV7gLHStIucLZwzkFrNwvjbJqiTnsuA1qiHWKpn0pUED/bXuwjnVc4pH4oij8SJTm205uipsjhcPjNcDicyR//+//81+cQO08wzVAcXbuXswvXgZEfByjaXbs52f70s/vrL3/9y/xjED473+p+b1g/OjLKrt1HQpJ3npf5jzAE2SxEfhpn8ZbM/Dj0QBB7VxcX//IuLz1ISbiUluPMv+QRQSEsftCfizjyYUJygG/jAOKsaqdf1gVV5xMIYZYAH167v6MU+img9H+Hm1nZ33XeYwQoL2uIt66TvH33NYNrksbRbp0AggC+3yeQft8CnMGK83fJW1vmL64Y8x6IophQcnE0avEuXxZd2EcqALJnbBWLu3Y/p3GQ+0TsRLv9BvetBtpEOyYwJfsvcFsNTcqhq6XreO3hnjyej1aHMl6u3VVE3ly5zqccY7DBkIuMynRN4hT+G0YwBQQGnwEhMKVYWAWwWIsyuTRVRP+tZ6F7QwHmOjfoGQb/gdGOPPKZbsFz3fJPirKvEaJwpGNImkORsfJ395xJinw+6TLO6UDN2rppBDDzU5SU2z6IffrfifwzJVkTECZ8DVT09yi0WMUn8IR2BVglmluEIdWYLxAXX7NHlJSKM6sg+FD1uEnj8EuMG2yWHx7WcZ4WUo11X+9BuoOkzc7ca+BuowTL2B+jBxscb1QlOLTK1LN060sfLi3VbpQUF3lG4hCmY2ToV2PHSEYc+9qsidW2bVBKHpdgP1wbj6DXyWNMYq1e13h4qLo0it3+omi29Fmn2l0cxWlAHYZuluo+Gp7KT2amqu+TDM4HqsyHMzWHMh4nUo/J+hEAAupZP6AIpHu7M3Ko9tAJ+OIYmtgu3heNR9JDa3zdMYyOAVgB7jEI4wNfGmIByvyY+vET3Sv7Q6ObTkY98zxrwaIQ/rpqH0iuECNDwyltvUQJBEEKs2ygXr8dodfmQ6Z0XPRGvZD3"
                       + "Q9OlsentL4pJlz4PPWdqCE09aep5TSdNzfZ4S7AiMDzoDe+wtmOUWzraBHUT+Z6DygwNotKHXDNw2d488F4SdsWPevi2egzzSfJQ8kjKs2yV3WCwa6IWXyM6Dd5TnRcl0l7+LQw3MK1IrUKwo+O+AZzTXxeKrFqd2Z2r7nrZ3fUbCmDMO191d74jj0wzq85vVJmUq++QSMuMTxbKNsf0oophYCsYagOSROjeI5wERkFhlvXi0a/4fZbFPipg2b4JV3fx9nwfo8DpvJg3R2AdVXJuc0xQgpFPEcjWIFuRu2gJMSTQee+TIsS3AJkPAlXBKP+BHTvcnCrsFFhrc/QPZSJqz2DKXBGAF1RbSQpQRFTjhyIfJQB3CUQaNNjCenwW+csSsu2mTHYJYPL0fBZpJ/okNPcEXHXDTboimjbYdF9sdpjHHnr310hVg5vimiZRvJjNLmXdsl6vavFNzHWYf8nTLA73Acs2HxtHVuBRmmbk/njaZtya16BxkrPcCRKN5yxh70gG3uCoj9OE8bBT5GGz4QaveDjilPVPnP2Y5r26BPVaYjn21m/gXwhxxjtajwIcCG4GgdjsuDmSPghyBgFM5+DgsCuvN3QMoSO4P7z+jpcb1gif1UOWDVhDogQXmpuSfAwqp2mbRONgdlAp3M8eQrXsdGQaFeghwqK9OgKlO9MzuI5XKKMrvPcM54bYSKK00hIZYW8VqdYPg0If7cuhDLW++wpnXYSAAti+a4ZApYUC2di0V2ixevn5RF1+l/ds4z8LrAu465CAwWMW6FTQm7x4TWhEXX+PN23pTwvci+DtEIPZg7aA1FhhCAFOgyQMXp2NXyfwXet/3/pVd8xKkFMUoWatQxN0joaVqzFeFyQPoVeUHRKoY3X8MOPf5l6ZklQ1zD1D7tL8FiQJinZCLlPV4qzLRKbFT+vhaURhScPzM002EeeWz0TiFOyg9JVOTTm9QWlGloCADWBxtEUQKt1sju56KukEV7er"
                       + "PoHqAez/5SBdRhc/8FU/pyJwQ1cWMjepeMZSjb860mHpZACD1Bz1XsQ4D6PeC6KZVvnuKpIpW+wpVClLbU6Q/OzQTaOVsiRSan2wpyc8YYnUhGaV1tyTNkpxQBVMKLeCNsasECge/YcCoZKOVFCzxKF2sEnQdXqAKGVTVlMXhIYD+kTb1Zj4yZulz3qy2irzUJOIxauVKOOuK5eZ2nSr0WQmtaDDW39IXS993MnAUXOArECjH/aymj0dKGWKTutMKFoGAKR4nGxho2j5ISFmdGMHYkyTB1QQ6gOZYZxJsjzKKMrVGHrsQAnP7WkhhbfaUzqsoayTfERKdZs9FSG3R5FT2fyyWDbR4vk9IiXeeDY6IdwpD6MXalZMQcxKN/Rjj+HqH0rXmkQXkVDTevx9b1+L25svB8MsnbK6u63nxe73kpz0MS9VONbHb0nHWDTgCSwM5s74TnAwI9nJH720B6h4/1llLGOKp8vYrl+Ojag4UUIkcheOUh4qkUIi8yo80V/zpcQryi6uQ9f/hIIiVrHPqCWYsQ6z9Xe8wAiyg6rucAsitIUZuY//C6Nr9+ri4mepaGxEQZeXZQF+FVVdiMmiN993YIZe6XqWE0RPIPUfQaoUXEyo19riGJBDlGvVzP0tBM9/n1yCRf1lSA6YIm6KE5xvzVOBpqkVT/1EXmG90zno2ahKJktQH049NAhpHUdakKj6+koKfU6Fi+HAEEt4KM1NUcWjGM7BZTpjTMaLW96TF+e8CCzkupxxx6jBtk0qyhlDQanDOQNLJdXhaHXvba/u/diVI6P3ehoJuWpkvJcxMSX/9Fn4RZbTCXLvj59ur3+fO7+UX8sk+zI7bHD2u6NLihiZmz9q/w3vKAPuLMOzIu32vSfQc4YJuKdMua3yC4+cYXvMnFrTa8zJU2inFKqc/uARskqPWBFw/GOn69Hi/E6dIYUmpy0sOTp07O3AwYpHrGFzzIIRfea+miUo7542974re7+M29Or"
                       + "14Y9HZU++WdTfq45t78ntb9jFm1KuDxRc952pP7rJlmYElaVKUqXzlAYoCP9QZvPrU36N5cM6Ajf6XNjjeUE3dUExhn0OchHqTbQlQbY1BcIQJMT+s6qqEDEUpOZZJMy3RplrGo5k0RxK2Z1R5qSTnOGVRFjoaqopZQZcX41D/378UILHJDTrz5M08NV+JOl9GjP0K4hwd7bI+i3jlXeZxVt4/p4lziqu0hBrFtIAIvDv08J2gKf0M8+zDLxr0p8DDcwWEV3OUlyQpcMww1u5YowL6Fr/qJwoc3z/K54Nc0OsQTKJmLx1bvoQ45w88czbjQBOAMJ5n5UYXG2l4SFx3d7TulTHFkSqsTHvaZ7GCaYEsvuojV4gmbe+mXYlth8icAuBWFW0WjG058UfkH4/MufuA8ODHRXAAA="; }
        }
    }
}
