// <auto-generated />
namespace Wirecraft.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class inita : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207190948550_inita"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAN1c227cOBJ9X2D+oaGnnQXGspMskA3aM0i644ExaztIO5nHgC2x28RIokaiDPe37cN+0vzCkLpQFC8SdbG645cgzUuRrDosVlGH/ut//1/+8hQGi0eYpAhHl87F2bmzgJGHfRTtL52M7H566/zy8w//WH70w6fF16rda9aO9ozSS+eBkPid66beAwxBehYiL8Ep3pEzD4cu8LH76vz8P+7FhQupCIfKWiyWn7OIoBDmP+jPFY48GJMMBDfYh0FaltOaTS51cQtCmMbAg5fO7yiBXgKo/N/h9qxo7yzeBwjQuWxgsHMW8Zt3X1K4IQmO9psYEASC+0MMaf0OBCksZ/4ufmM7+fNXbPIuiCJMqDgcDVq8w5dFF/aRKoAc2LTyxV06nxLsZx4RG9Fmv8FDo4AW0YYxTMjhM9yVXeOi6/XaWbjN7q7cn/dWu7K5XDrXEXn9ylncZkEAtgHkKqM63RCcwF9hBBNAoP8JEAITioVrH+ZrUQaXhorov9Uo1DYUYM7iCj1B/78w2pMHPtINeKpK/k1R9iVCFI60D0kyKE6s+N0+Zpwgjw+6xhntqFlbuwwfpl6C4sLsvaZP/zty/myTbAgIY74Gqvp7FFqs4hY8on0OVknmDgWQ7pjPMMhr0wcUFxvnrITgt7LFVYLDzziosVlUfNvgLMm1inW19yDZQ9KcztKt4W6zCdbYG7IPtgHeqptg6i1TjdK+X7pwabntbI1aChxj1spwerNWRredENNS22yoib8VbZT5VFUmoPH6UVD7wAafDGRTweZIbrbNz9o5SUBANeoHFIHkYOcdew5D6AB8cQxNzIr3eWFfSQM9qzW+VllKcAiTIRjzyr5DcCb2PUmsjYXaFiXkYQ0O/Y9E2Wc+YIJv+y9h/LGej7wevWWOFUHgxKeJgNa7V6j/VrWpvbtUpXh3uX6Ud79jMoZsvXzwIfuOd3zuTeej1MM0fxoZ1tr7iXY5Kc2IsrThlHPl"
                       + "b8rynuJyNTKMjt7eI5AvSQK+n8A07ekm3gw4VbviO/2my/V9TWBYbB1x00lVSpAn1/cN8yoUjXUG8rxMzmK4M2CLnDS5ntZ9DM0IhnmhdiF/ZqD0RNMkJyUqxyFXPi5MyJ4iY6pl81a6iZWVLVOrWvQ7y7JQylOKCPc6vQrAvr7F+hLRYYID9UWimZrLv4HhFialqOsQ7Gm/ryDI6K9zRVeNxiwHr5petDf9inyIeeNX7Y3vyAMzdNn4taqTYvUtGmkcL6OVsssCmuEG0LdVDHVMcSw071BODCM/Py706tGv+H2aYg/lsFRuRoq0uTnix8hfdOTQ9fEsXLIsbrKAoDhAHgXipfMvZSlmwdxjN5MxWeSFIzvNu2gNA0jg4r1H8svkFUg94Kv+hGrGb5ZQPwsTFiWBYEU3LEkAiojqlFHkoRgE7ROXuvW7UHL5IHLNGjKD0zm222Pc6HwQSWFd+lm6ArCs8FZeGnWAQr4YVLD2rKgwTUeD0D7QHwO2pkJsjN0WZvRGW1MBo4efAW5yIGCysDEqkLKPPNrr4d2McbIk9/Tcm2HmNkY3BKu9EGcwyMjhZ0VcFeN1Y0MJ+CZDnRwozuxCRyJPmv18/s5omu/B58npsQklxouzGiP8snmec9aYvXd4y4kOWYNCbGxuvlnvhTuDAsbPYHLYFTkm7UNoD56UbP4M1ltWCJ9Uv8c6bCBRbp7qdFX2TIqD04qgUVeLlDwm6xDEImKdiCLx6OhcKV4noN4/HUKqmyxFQon3ju7cXxlFFEeIJEawbS1L+ZAqtDJ8a5Xh1p028gVIVlSQ250oCqJKO8oep7lMexVUX7aNCtBlMRZ5jLp4q5VL6YedCgesXrk8U9ffGlZbBdbC7EXwtmjBFEoLkqpdNKEK+EVdmxK0kZ5lrDdGEXJ0ZwGsAcpQrttVVbSGHFZBhzB1waG2aMEUK4yBQ3V1yo81Xrd0C8ZgWbB0DdTC5Q2IYxTtBaphWbLYFDzD1U+b"
                       + "/iy/sJDheg3VyocwH4ngBOyhVEuHpjO9QklK2CfiLWDXmis/VJrZHOLVUNJZrpqrOouqDuz/RScd4ZIf/WrEUwq4oisLWcCUf+0UjG3suWBsTxCAxPxlZIWDLIw6o3ezrIKwIIopSuwllIzC5kyQ+smsTUaDUShKalTYyxO+dIrShGJV1tKVDKWEogomlPygibE+CMxPwKlAqLAFc2mWONR2Nim6upEVtWy6pW2DUH9AH8lcRaA22lAq187KRPpuz2uc8R6ioMI1tnVe0mM/55/7Gls5L3mRHqGOIkbDTE+5y2V1Qc3c1aRiMY8XddyW35uljYddTYtrbABe2sM/1by4hn+qi3vKWis7Qih+kaA2htc9Ea2hseWCuuBs6GfSLL+JF/VqvJ43y6mpaQ33x0vtJU27uyqOmiipKrOXIlDTFD0Vxc+LZZMsTk8TJfHCk9kTQtY8zb5QGV25MKu9oe87Rwoy1V6rSVqioLp0ZrsrKbnchI/OU3MpBV+W6XD3E0AlPy6aOAuqokfk57nxIaUWPmMNzmievAoQZA6oanADIrSDKbnHf8Do0qHp+1vpDeGA931umvrBd/HIDzFddNKQe7IGi4ClGCB6BIn3ABKF+j/i+d4uwIBM8Xqvmtw/Q/D042g+PQ3uIZnw3YgpLz3dJ3A5msY+gOsW8p287DrW3jof9WaLytzmb1CUTdH7XdYQODz7rjqd11in4HsHvbOyNIlmr8vvrEY5YOXtlBm6J+HPj/4S6VkAJz9CGnY4G3bHqBdIQyQoj44GY30onFRJ0qMj7a5+0+n1X/YbmcG2HidCfh8zPHYZzvMvKC9zku91DI95ydWGzwg9ouAhvP0XxtU/Pj1/dtyYP1Y/Fy+1J3q+NybqMbmnJdFuZqrpnORS06X/0bmkI59tzPyaQkPEGsrYH06Pn/8dxot6enH8M+s42Jn/xOqHn3kPLD2HXWXJyTZscq85bsw89uI7Ak3atpiau4jmP5kImgb5"
                       + "eRjTSnJvGUXLDJYHKiJ9AwleJ/yDlm4ti63P8RZ6vE78ysQD1dPfzeR5nfA7PTfUSKxv59UbR9CyeWfg3Yu2rDlPdvT6Rj+x+OR49bqZHn2Rz0KXbkzX9KpEFxop5I1TfB/QPU3T2an9/n6C/P+hgJ1uqT247eoHc3rICn9Zlx7yKdrXItjf2Y2g1zheeZvraIerg16aUdVEuga7gQSwb0jvE4J2wCO02oNpKv6xi4/hFvrX0V1G4ozQJcNwGzS4CSxaaBs/J/A357y8y7/mplMsgU4TsRvau+hDhoL6b3pcaa7wDCJYGFJerDNbEnbBvj9wSbc4shRUqo9HT/cwjAMqLL2LNuARmufWrcOmxpZrBPYJCNNSRt2f/qTw88Onn/8GPynqMxtaAAA="; }
        }
    }
}
